============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-8.3.3, pluggy-1.5.0 -- /home/smy154/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python
cachedir: .pytest_cache
rootdir: /home/smy154/code/smy154/data-train-in-the-cloud/tests
configfile: pytest_kitt.ini
collecting ... collected 9 items / 1 deselected / 8 selected

tests/cloud_training/test_cloud_data.py::TestCloudData::test_big_query_dataset_variable_exists PASSED [ 12%]
tests/cloud_training/test_cloud_data.py::TestCloudData::test_cloud_data_create_dataset PASSED [ 25%]
tests/cloud_training/test_cloud_data.py::TestCloudData::test_cloud_data_create_table PASSED [ 37%]
tests/cloud_training/test_main.py::TestMain::test_route_preprocess PASSED [ 50%]
tests/cloud_training/test_main.py::TestMain::test_route_train[local] PASSED [ 62%]
tests/cloud_training/test_main.py::TestMain::test_route_train[gcs] PASSED [ 75%]
tests/cloud_training/test_main.py::TestMain::test_route_evaluate PASSED  [ 87%]
tests/cloud_training/test_main.py::TestMain::test_route_pred PASSED      [100%]

================ 8 passed, 1 deselected, 19 warnings in 25.27s =================
